name: Build
on:
  push:
    branches:
    - master
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go
      uses: actions/setup-go@v1
      with:
        go-version: 1.12
      id: go

    - name: Check out code
      uses: actions/checkout@v1

    - name: Test
      run: go test -cover -v ./...

    - name: Build
      run: go build -v .

    - name: Package
      env:
        BUILD:
      run: ./script/package.sh

    - name: Upload
      uses: actions/aws/cli@master
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        BUCKET: ${{ secrets.BUCKET }}
      with:
        args: s3 sync --acl public-read ./build/ s3://${BUCKET}/

    - name: Build Docker Image
      uses: actions/docker/cli@master
      with:
        args: build --build-arg BUILD= -t ${{ secrets.DOCKER_USERNAME }}/atlas:latest .

    - name: Docker Login
      uses: actions/docker/login@master
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

    - name: Publish Docker Image
      uses: actions/docker/cli@master
      with:
        args: push ${{ secrets.DOCKER_USERNAME }}/atlas:latest

    - name: Cleanup
      run: rm -rf $HOME/.docker/
